# Generated by Django 5.0.1 on 2024-01-31 08:31

import app_user.util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=255, validators=[app_user.util.validate_password])),
                ('phone_no', models.CharField(max_length=50, validators=[app_user.util.validate_phone_number])),
                ('email', models.CharField(max_length=255, validators=[app_user.util.validate_email])),
                ('gender', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'app_user_model',
            },
        ),
    ]
